### ISSUE TITLE
HttpUtils工具类侵权 请尽快删除

### ISSUE THREAD

**Issue by zjhzhangjiahao** [hnjd-team/MoGuDing#4]
经安全扫描  您的httpUtil工具类侵犯公司代码  为避免不必要的麻烦 请尽快删除此代码 谢谢合作

**Comment by Hei-Joy** [comment]
你可以加我QQ:1091251415或者微信:15570711575私聊我------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;zjhzhangjiahao&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年6月8日(星期一) 晚上6:58
收件人:&nbsp;&quot;hnjd-team/MoGuDing&quot;<MoGuDing@noreply.github.com&gt;;
抄送:&nbsp;&quot;Subscribed&quot;<subscribed@noreply.github.com&gt;;
主题:&nbsp;[hnjd-team/MoGuDing] HttpUtils工具类侵权 请尽快删除 (#4)
